In [2]:
!pip install requests

Collecting requests
  Downloading requests-2.33.1-py3-none-any.whl.metadata (4.8 kB)
Collecting charset_normalizer<4,>=2 (from requests)
  Downloading charset_normalizer-3.4.7-cp313-cp313-macosx_10_13_universal2.whl.metadata (40 kB)
Collecting idna<4,>=2.5 (from requests)
  Downloading idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting urllib3<3,>=1.26 (from requests)
  Downloading urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests)
  Downloading certifi-2026.2.25-py3-none-any.whl.metadata (2.5 kB)
Downloading requests-2.33.1-py3-none-any.whl (64 kB)
Downloading certifi-2026.2.25-py3-none-any.whl (153 kB)
Downloading charset_normalizer-3.4.7-cp313-cp313-macosx_10_13_universal2.whl (309 kB)
Downloading idna-3.11-py3-none-any.whl (71 kB)
Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
Installing collected packages: urllib3, idna, charset_normalizer, certifi, requests
Successfully installed certifi-2026.2.25 charset_normalizer-3.4.7 idna-3.11 requests-2.33.1 urllib3-2.6.3

In [ ]:
#Cut 1 Spectral Download
import os
import time
from pathlib import Path

import numpy as np
import pandas as pd
import requests
from astropy.table import Table

# ----------------------------
# User settings
# ----------------------------
ID_FILE = "apogee_ids_2M_Cut_1.txt"
ALLSTAR_FILE = "allStar-dr17-synspec_rev1.fits"
OUTPUT_DIR = "apogee_apStar_dr17"
SLEEP_BETWEEN = 0.1

# ----------------------------
# Load APOGEE IDs from text file
# ----------------------------
with open(ID_FILE, "r") as f:
    ids = [line.strip() for line in f if line.strip()]

# remove duplicates while preserving order
ids = list(dict.fromkeys(ids))

print(f"Loaded {len(ids)} APOGEE IDs")

# ----------------------------
# Read allStar and recover FIELD/TELESCOPE
# ----------------------------
tab = Table.read(ALLSTAR_FILE, hdu=1)

tab_ids = np.array([str(x).strip() for x in tab["APOGEE_ID"]])

want = set(ids)
rows = []

for row, apid in zip(tab, tab_ids):
    if apid in want:
        rows.append({
            "APOGEE_ID": apid,
            "FIELD": str(row["FIELD"]).strip(),
            "TELESCOPE": str(row["TELESCOPE"]).strip(),
        })

meta = pd.DataFrame(rows).drop_duplicates(subset=["APOGEE_ID"])
meta = meta.set_index("APOGEE_ID").reindex(ids).reset_index()

missing = meta["FIELD"].isna() | meta["TELESCOPE"].isna()
if missing.any():
    print("\nIDs not found in allStar:")
    for apid in meta.loc[missing, "APOGEE_ID"]:
        print(apid)

meta = meta.loc[~missing].copy()
print(f"Found FIELD/TELESCOPE for {len(meta)} IDs")

display(meta.head())

# ----------------------------
# Make output directory
# ----------------------------
output_dir = Path(OUTPUT_DIR)
output_dir.mkdir(parents=True, exist_ok=True)

# ----------------------------
# DR17 apStar base URL
# ----------------------------
base = "https://data.sdss.org/sas/dr17/apogee/spectro/redux/dr17/stars"

# ----------------------------
# Download helper
# ----------------------------
def download_file(url, outpath):
    if outpath.exists():
        print(f"Already exists: {outpath.name}")
        return True

    try:
        r = requests.get(url, stream=True, timeout=60)
        if r.status_code != 200:
            print(f"Failed ({r.status_code}): {url}")
            return False

        with open(outpath, "wb") as f:
            for chunk in r.iter_content(chunk_size=8192):
                if chunk:
                    f.write(chunk)

        print(f"Saved: {outpath.name}")
        return True

    except Exception as e:
        print(f"Error downloading {url}: {e}")
        return False

# ----------------------------
# Download all spectra
# ----------------------------
success = 0
failed = 0

for _, row in meta.iterrows():
    apogee_id = row["APOGEE_ID"]
    field = row["FIELD"]
    telescope = row["TELESCOPE"]

    filename = f"apStar-dr17-{apogee_id}.fits"
    url = f"{base}/{telescope}/{field}/{filename}"
    outpath = output_dir / filename

    ok = download_file(url, outpath)
    if ok:
        success += 1
    else:
        failed += 1

    time.sleep(SLEEP_BETWEEN)

print(f"\nDone. Success: {success}, Failed: {failed}")

Loaded 111 APOGEE IDs
Found FIELD/TELESCOPE for 111 IDs

            APOGEE_ID   FIELD TELESCOPE
0  2M08263810-1806097  240+12    lco25m
1  2M08264174-1805195  240+12    lco25m
2  2M08264810-1810234  240+12    lco25m
3  2M08264981-1808416  240+12    lco25m
4  2M08265265-1806186  240+12    lco25m

Failed (404): https://data.sdss.org/sas/dr17/apogee/spectro/redux/dr17/stars/lco25m/240+12/apStar-dr17-2M08263810-1806097.fits
Failed (404): https://data.sdss.org/sas/dr17/apogee/spectro/redux/dr17/stars/lco25m/240+12/apStar-dr17-2M08264174-1805195.fits
Failed (404): https://data.sdss.org/sas/dr17/apogee/spectro/redux/dr17/stars/lco25m/240+12/apStar-dr17-2M08264810-1810234.fits
Failed (404): https://data.sdss.org/sas/dr17/apogee/spectro/redux/dr17/stars/lco25m/240+12/apStar-dr17-2M08264981-1808416.fits
Failed (404): https://data.sdss.org/sas/dr17/apogee/spectro/redux/dr17/stars/lco25m/240+12/apStar-dr17-2M08265265-1806186.fits
Failed (404): https://data.sdss.org/sas/dr17/apogee/spectro/redux/dr17/stars/lco25m/240+12/apStar-dr17-2M08265861-1808089.fits
Failed (404): https://data.sdss.org/sas/dr17/apogee/spectro/redux/dr17/stars/lco25m/240+12/apStar-dr17-2M08265916-1813079.fits
Failed (404): https://data.sdss.org/sas/dr17/apogee/spectro/redux/dr17/stars/lco25m/240+12/apStar-dr17-2M08270183-1804120.fits
Failed (404): https://data.sdss.org/sas/dr17/apogee/spectro/redux/dr17/stars/lco25m/240+12/apStar-dr17-2M08270312-1811400.fits
Failed (404): https://data.sdss.org/sas/dr17/apogee/spectro/redux/dr17/stars/lco25m/240+12/apStar-dr17-2M08270680-1802165.fits
Failed (404): https://data.sdss.org/sas/dr17/apogee/spectro/redux/dr17/stars/lco25m/240+12/apStar-dr17-2M08271045-1813311.fits
Failed (404): https://data.sdss.org/sas/dr17/apogee/spectro/redux/dr17/stars/lco25m/240+12/apStar-dr17-2M08271567-1808353.fits
Failed (404): https://data.sdss.org/sas/dr17/apogee/spectro/redux/dr17/stars/lco25m/240+12/apStar-dr17-2M08272439-1804522.fits
Failed (404): https://data.sdss.org/sas/dr17/apogee/spectro/redux/dr17/stars/lco25m/240+12/apStar-dr17-2M08273086-1810478.fits
Failed (404): https://data.sdss.org/sas/dr17/apogee/spectro/redux/dr17/stars/lco25m/240+12/apStar-dr17-2M08273090-1812129.fits
Failed (404): https://data.sdss.org/sas/dr17/apogee/spectro/redux/dr17/stars/lco25m/240+12/apStar-dr17-2M08273166-1806317.fits
Failed (404): https://data.sdss.org/sas/dr17/apogee/spectro/redux/dr17/stars/lco25m/240+12/apStar-dr17-2M08273243-1805101.fits
Failed (404): https://data.sdss.org/sas/dr17/apogee/spectro/redux/dr17/stars/lco25m/240+12/apStar-dr17-2M08280905-1809470.fits
Failed (404): https://data.sdss.org/sas/dr17/apogee/spectro/redux/dr17/stars/lco25m/240+12/apStar-dr17-2M08281371-1810583.fits
Failed (404): https://data.sdss.org/sas/dr17/apogee/spectro/redux/dr17/stars/lco25m/240+12/apStar-dr17-2M08281388-1801106.fits
Failed (404): https://data.sdss.org/sas/dr17/apogee/spectro/redux/dr17/stars/lco25m/240+12/apStar-dr17-2M08282165-1802041.fits
Failed (404): https://data.sdss.org/sas/dr17/apogee/spectro/redux/dr17/stars/lco25m/240+12/apStar-dr17-2M08283252-1806575.fits
Failed (404): https://data.sdss.org/sas/dr17/apogee/spectro/redux/dr17/stars/lco25m/240+12/apStar-dr17-2M08284344-1801092.fits
Failed (404): https://data.sdss.org/sas/dr17/apogee/spectro/redux/dr17/stars/lco25m/240+12/apStar-dr17-2M08284866-1810322.fits
Failed (404): https://data.sdss.org/sas/dr17/apogee/spectro/redux/dr17/stars/lco25m/240+12/apStar-dr17-2M08285629-1801406.fits
Failed (404): https://data.sdss.org/sas/dr17/apogee/spectro/redux/dr17/stars/lco25m/240+12/apStar-dr17-2M08290598-1805565.fits
Failed (404): https://data.sdss.org/sas/dr17/apogee/spectro/redux/dr17/stars/lco25m/240+12/apStar-dr17-2M08290951-1807201.fits
Failed (404): https://data.sdss.org/sas/dr17/apogee/spectro/redux/dr17/stars/lco25m/240+12/apStar-dr17-2M08291059-1802302.fits
Failed (404): https://data.sdss.org/sas/dr17/apogee/spectro/redux/dr17/stars/lco25m/240+12/apStar-dr17-2M08291447-1806290.fits
Failed (404): https://data.sdss.org/sas/dr17/apogee/spectro/redux/dr17/stars/lco25m/240+12/apStar-dr17-2M08291599-1808187.fits
Failed (404): https://data.sdss.org/sas/dr17/apogee/spectro/redux/dr17/stars/lco25m/240+12/apStar-dr17-2M08292703-1806350.fits
Failed (404): https://data.sdss.org/sas/dr17/apogee/spectro/redux/dr17/stars/lco25m/240+12/apStar-dr17-2M08292865-1801137.fits
Already exists: apStar-dr17-2M08313774-2044159.fits
Already exists: apStar-dr17-2M08313948-2049340.fits
Already exists: apStar-dr17-2M08314033-2045418.fits
Already exists: apStar-dr17-2M08314056-2051062.fits
Already exists: apStar-dr17-2M08314088-2058127.fits
Already exists: apStar-dr17-2M08314312-2052081.fits
Already exists: apStar-dr17-2M08314570-2035331.fits
Already exists: apStar-dr17-2M08315521-2059494.fits
Already exists: apStar-dr17-2M08321168-2051391.fits
Already exists: apStar-dr17-2M08321319-2043170.fits
Already exists: apStar-dr17-2M08322001-2051184.fits
Already exists: apStar-dr17-2M08322656-2021128.fits
Already exists: apStar-dr17-2M08322878-2054000.fits
Already exists: apStar-dr17-2M08323600-2051321.fits
Already exists: apStar-dr17-2M08323780-2050066.fits
Already exists: apStar-dr17-2M08324299-2016522.fits
Already exists: apStar-dr17-2M08324710-2020078.fits
Already exists: apStar-dr17-2M08325349-2045139.fits
Already exists: apStar-dr17-2M08325825-2012378.fits
Already exists: apStar-dr17-2M08330394-2028122.fits
Already exists: apStar-dr17-2M08330574-2035029.fits
Already exists: apStar-dr17-2M08331081-2013217.fits
Already exists: apStar-dr17-2M08331654-2018448.fits
Already exists: apStar-dr17-2M08331835-2029070.fits
Already exists: apStar-dr17-2M08331912-2014412.fits
Already exists: apStar-dr17-2M08332169-2043474.fits
Already exists: apStar-dr17-2M08332793-2040359.fits
Already exists: apStar-dr17-2M08333121-2047028.fits
Already exists: apStar-dr17-2M08333812-2033151.fits
Already exists: apStar-dr17-2M08334573-2048405.fits
Already exists: apStar-dr17-2M08335104-2012328.fits
Already exists: apStar-dr17-2M08335210-2051359.fits
Already exists: apStar-dr17-2M08335217-2020067.fits
Already exists: apStar-dr17-2M08335463-2047536.fits
Already exists: apStar-dr17-2M08335572-2041562.fits
Already exists: apStar-dr17-2M08335791-2004002.fits
Already exists: apStar-dr17-2M08340229-2014376.fits
Already exists: apStar-dr17-2M08340273-2031397.fits
Already exists: apStar-dr17-2M08340323-2027066.fits
Already exists: apStar-dr17-2M08340648-2021599.fits
Already exists: apStar-dr17-2M08340829-2054073.fits
Already exists: apStar-dr17-2M08341165-2046019.fits
Already exists: apStar-dr17-2M08341283-2015547.fits
Already exists: apStar-dr17-2M08341342-2051003.fits
Already exists: apStar-dr17-2M08341920-2035068.fits
Already exists: apStar-dr17-2M08341967-2057116.fits
Already exists: apStar-dr17-2M08341998-2048551.fits
Already exists: apStar-dr17-2M08342651-2027023.fits
Already exists: apStar-dr17-2M08342691-2037197.fits
Already exists: apStar-dr17-2M08343072-2026076.fits
Already exists: apStar-dr17-2M08343237-2039170.fits
Already exists: apStar-dr17-2M08343579-2016359.fits
Already exists: apStar-dr17-2M08343602-2054461.fits
Already exists: apStar-dr17-2M08343773-2041329.fits
Already exists: apStar-dr17-2M08343893-2020390.fits
Already exists: apStar-dr17-2M08343924-2059116.fits
Already exists: apStar-dr17-2M08344205-2028480.fits
Already exists: apStar-dr17-2M08344493-2059058.fits
Already exists: apStar-dr17-2M08344923-2055307.fits
Already exists: apStar-dr17-2M08345249-2039210.fits
Already exists: apStar-dr17-2M08345319-2026466.fits
Already exists: apStar-dr17-2M08345402-2056053.fits
Already exists: apStar-dr17-2M08350220-2037544.fits
Already exists: apStar-dr17-2M08350479-2039118.fits
Already exists: apStar-dr17-2M08350785-2042121.fits
Already exists: apStar-dr17-2M08351453-2025370.fits
Already exists: apStar-dr17-2M08351559-2052058.fits
Already exists: apStar-dr17-2M08351668-2048222.fits
Already exists: apStar-dr17-2M08352535-2055023.fits
Already exists: apStar-dr17-2M08352980-2030481.fits
Already exists: apStar-dr17-2M08353222-2059001.fits
Already exists: apStar-dr17-2M08353664-2042480.fits
Already exists: apStar-dr17-2M08353666-2031465.fits
Already exists: apStar-dr17-2M08353880-2029321.fits
Saved: apStar-dr17-2M08354359-2044500.fits
Saved: apStar-dr17-2M08354523-2051073.fits
Saved: apStar-dr17-2M08355473-2058421.fits
Saved: apStar-dr17-2M08355771-2004513.fits
Saved: apStar-dr17-2M08355804-2039263.fits

Done. Success: 79, Failed: 32

In [10]:
df2 = pd.read_csv("apogee_stars_RA_Dec_cut2_smaller.csv", sep=',')
df2['APOGEE_ID']
df2['APOGEE_ID'].to_csv('apogee_ids_2M_Cut_2.txt', index=False, header=False, sep='\t')

In [11]:
#Cut 2 Spectral Download
import os
import time
from pathlib import Path

import numpy as np
import pandas as pd
import requests
from astropy.table import Table

# ----------------------------
# User settings
# ----------------------------
ID_FILE = "apogee_ids_2M_Cut_2.txt"
ALLSTAR_FILE = "allStar-dr17-synspec_rev1.fits"
OUTPUT_DIR = "apogee_apStar_dr17_cut2"
SLEEP_BETWEEN = 0.1

# ----------------------------
# Load APOGEE IDs from text file
# ----------------------------
with open(ID_FILE, "r") as f:
    ids = [line.strip() for line in f if line.strip()]

# remove duplicates while preserving order
ids = list(dict.fromkeys(ids))

print(f"Loaded {len(ids)} APOGEE IDs")

# ----------------------------
# Read allStar and recover FIELD/TELESCOPE
# ----------------------------
tab = Table.read(ALLSTAR_FILE, hdu=1)

tab_ids = np.array([str(x).strip() for x in tab["APOGEE_ID"]])

want = set(ids)
rows = []

for row, apid in zip(tab, tab_ids):
    if apid in want:
        rows.append({
            "APOGEE_ID": apid,
            "FIELD": str(row["FIELD"]).strip(),
            "TELESCOPE": str(row["TELESCOPE"]).strip(),
        })

meta = pd.DataFrame(rows).drop_duplicates(subset=["APOGEE_ID"])
meta = meta.set_index("APOGEE_ID").reindex(ids).reset_index()

missing = meta["FIELD"].isna() | meta["TELESCOPE"].isna()
if missing.any():
    print("\nIDs not found in allStar:")
    for apid in meta.loc[missing, "APOGEE_ID"]:
        print(apid)

meta = meta.loc[~missing].copy()
print(f"Found FIELD/TELESCOPE for {len(meta)} IDs")

display(meta.head())

# ----------------------------
# Make output directory
# ----------------------------
output_dir = Path(OUTPUT_DIR)
output_dir.mkdir(parents=True, exist_ok=True)

# ----------------------------
# DR17 apStar base URL
# ----------------------------
base = "https://data.sdss.org/sas/dr17/apogee/spectro/redux/dr17/stars"

# ----------------------------
# Download helper
# ----------------------------
def download_file(url, outpath):
    if outpath.exists():
        print(f"Already exists: {outpath.name}")
        return True

    try:
        r = requests.get(url, stream=True, timeout=60)
        if r.status_code != 200:
            print(f"Failed ({r.status_code}): {url}")
            return False

        with open(outpath, "wb") as f:
            for chunk in r.iter_content(chunk_size=8192):
                if chunk:
                    f.write(chunk)

        print(f"Saved: {outpath.name}")
        return True

    except Exception as e:
        print(f"Error downloading {url}: {e}")
        return False

# ----------------------------
# Download all spectra
# ----------------------------
success = 0
failed = 0

for _, row in meta.iterrows():
    apogee_id = row["APOGEE_ID"]
    field = row["FIELD"]
    telescope = row["TELESCOPE"]

    filename = f"apStar-dr17-{apogee_id}.fits"
    url = f"{base}/{telescope}/{field}/{filename}"
    outpath = output_dir / filename

    ok = download_file(url, outpath)
    if ok:
        success += 1
    else:
        failed += 1

    time.sleep(SLEEP_BETWEEN)

print(f"\nDone. Success: {success}, Failed: {failed}")

Loaded 3413 APOGEE IDs
Found FIELD/TELESCOPE for 3413 IDs

            APOGEE_ID       FIELD TELESCOPE
0  2M16200012+2733344  046+45_MGA    apo25m
1  2M16200058+2638119  043+44_MGA    apo25m
2  2M16200096+3029038  049+46_MGA    apo25m
3  2M16200130+3054529  052+44_MGA    apo25m
4  2M16200198+2825014  048+44_MGA    apo25m

Saved: apStar-dr17-2M16200012+2733344.fits
Saved: apStar-dr17-2M16200058+2638119.fits
Saved: apStar-dr17-2M16200096+3029038.fits
Saved: apStar-dr17-2M16200130+3054529.fits
Saved: apStar-dr17-2M16200198+2825014.fits
Saved: apStar-dr17-2M16200223+3323551.fits
Saved: apStar-dr17-2M16200263+3300390.fits
Saved: apStar-dr17-2M16200295+2810183.fits
Saved: apStar-dr17-2M16200351+3111508.fits
Saved: apStar-dr17-2M16200366+2757487.fits
Saved: apStar-dr17-2M16200528+3240432.fits
Saved: apStar-dr17-2M16200550+3313093.fits
Saved: apStar-dr17-2M16200675+2811476.fits
Saved: apStar-dr17-2M16200695+2625173.fits
Saved: apStar-dr17-2M16200725+2804191.fits
Saved: apStar-dr17-2M16200818+3115377.fits
Saved: apStar-dr17-2M16201057+3130398.fits
Saved: apStar-dr17-2M16201156+2900436.fits
Saved: apStar-dr17-2M16201263+3226245.fits
Saved: apStar-dr17-2M16201277+3057381.fits
Saved: apStar-dr17-2M16201277+2545026.fits
Saved: apStar-dr17-2M16201504+2541172.fits
Saved: apStar-dr17-2M16201556+3104204.fits
Saved: apStar-dr17-2M16201596+2626557.fits
Saved: apStar-dr17-2M16201620+2601126.fits
Saved: apStar-dr17-2M16201734+3233338.fits
Saved: apStar-dr17-2M16201757+2630466.fits
Saved: apStar-dr17-2M16201939+2535134.fits
Saved: apStar-dr17-2M16201996+2941160.fits
Saved: apStar-dr17-2M16202072+2949414.fits
Saved: apStar-dr17-2M16202135+2839328.fits
Saved: apStar-dr17-2M16202211+3001235.fits
Saved: apStar-dr17-2M16202238+3231185.fits
Saved: apStar-dr17-2M16202346+3250114.fits
Saved: apStar-dr17-2M16202481+3128508.fits
Saved: apStar-dr17-2M16202575+2837391.fits
Saved: apStar-dr17-2M16202677+2656584.fits
Saved: apStar-dr17-2M16202689+3114372.fits
Saved: apStar-dr17-2M16202728+3332313.fits
Saved: apStar-dr17-2M16202768+3121437.fits
Saved: apStar-dr17-2M16202964+3008455.fits
Saved: apStar-dr17-2M16203067+3009193.fits
Saved: apStar-dr17-2M16203192+2507469.fits
Saved: apStar-dr17-2M16203206+3246565.fits
Saved: apStar-dr17-2M16203210+2859137.fits
Saved: apStar-dr17-2M16203221+2721407.fits
Saved: apStar-dr17-2M16203258+2650268.fits
Saved: apStar-dr17-2M16203266+2641167.fits
Saved: apStar-dr17-2M16203396+3145100.fits
Saved: apStar-dr17-2M16203413+2815395.fits
Saved: apStar-dr17-2M16203416+3132541.fits
Saved: apStar-dr17-2M16203719+2922105.fits
Saved: apStar-dr17-2M16203828+3043230.fits
Saved: apStar-dr17-2M16203840+3001190.fits
Saved: apStar-dr17-2M16203859+2718212.fits
Saved: apStar-dr17-2M16203949+2711496.fits
Saved: apStar-dr17-2M16203977+2602474.fits
Saved: apStar-dr17-2M16204053+3001538.fits
Saved: apStar-dr17-2M16204074+3014263.fits
Saved: apStar-dr17-2M16204151+2842045.fits
Saved: apStar-dr17-2M16204253+3251511.fits
Saved: apStar-dr17-2M16204259+2807299.fits
Saved: apStar-dr17-2M16204272+2533084.fits
Saved: apStar-dr17-2M16204491+2909394.fits
Saved: apStar-dr17-2M16204491+3029533.fits
Saved: apStar-dr17-2M16204541+3045244.fits
Saved: apStar-dr17-2M16204633+2732062.fits
Saved: apStar-dr17-2M16204650+3100332.fits
Saved: apStar-dr17-2M16204778+3251528.fits
Saved: apStar-dr17-2M16204865+2650061.fits
Saved: apStar-dr17-2M16204885+3001430.fits
Saved: apStar-dr17-2M16204905+3005455.fits
Saved: apStar-dr17-2M16204940+3135149.fits
Saved: apStar-dr17-2M16204962+2911190.fits
Saved: apStar-dr17-2M16205013+3109052.fits
Saved: apStar-dr17-2M16205022+3220497.fits
Saved: apStar-dr17-2M16205058+2558427.fits
Saved: apStar-dr17-2M16205088+2737569.fits
Saved: apStar-dr17-2M16205186+2708409.fits
Saved: apStar-dr17-2M16205233+3139411.fits
Saved: apStar-dr17-2M16205268+2702531.fits
Saved: apStar-dr17-2M16205341+2909073.fits
Saved: apStar-dr17-2M16205349+3112318.fits
Saved: apStar-dr17-2M16205392+2902324.fits
Saved: apStar-dr17-2M16205477+2627207.fits
Saved: apStar-dr17-2M16205478+2645565.fits
Saved: apStar-dr17-2M16205487+3228434.fits
Saved: apStar-dr17-2M16205572+3050259.fits
Saved: apStar-dr17-2M16205774+3231494.fits
Saved: apStar-dr17-2M16205785+3200539.fits
Saved: apStar-dr17-2M16205795+2905569.fits
Saved: apStar-dr17-2M16205841+2609493.fits
Saved: apStar-dr17-2M16210081+2734394.fits
Saved: apStar-dr17-2M16210111+2805040.fits
Saved: apStar-dr17-2M16210173+2654437.fits
Saved: apStar-dr17-2M16210196+3028338.fits
Saved: apStar-dr17-2M16210271+2512409.fits
Saved: apStar-dr17-2M16210280+3246472.fits
Saved: apStar-dr17-2M16210338+3301255.fits
Saved: apStar-dr17-2M16210354+3014432.fits
Saved: apStar-dr17-2M16210355+3025489.fits
Saved: apStar-dr17-2M16210374+3240135.fits
Saved: apStar-dr17-2M16210379+2536384.fits
Saved: apStar-dr17-2M16210394+2533024.fits
Saved: apStar-dr17-2M16210408+2630009.fits
Saved: apStar-dr17-2M16210469+2508001.fits
Saved: apStar-dr17-2M16210600+2944239.fits
Saved: apStar-dr17-2M16210611+2814163.fits
Saved: apStar-dr17-2M16210688+3041325.fits
Saved: apStar-dr17-2M16210714+3134367.fits
Saved: apStar-dr17-2M16210715+2552117.fits
Saved: apStar-dr17-2M16210741+2553060.fits
Saved: apStar-dr17-2M16210787+3205492.fits
Saved: apStar-dr17-2M16210830+3155207.fits
Saved: apStar-dr17-2M16210896+2920517.fits
Saved: apStar-dr17-2M16210923+2539227.fits
Failed (404): https://data.sdss.org/sas/dr17/apogee/spectro/redux/dr17/stars/apo25m/048+44_MGA/apStar-dr17-2M16210952+2931242.fits
Saved: apStar-dr17-2M16211033+2855524.fits
Saved: apStar-dr17-2M16211086+2515010.fits
Saved: apStar-dr17-2M16211096+2630456.fits
Failed (404): https://data.sdss.org/sas/dr17/apogee/spectro/redux/dr17/stars/apo25m/052+44_MGA/apStar-dr17-2M16211208+3103088.fits
Saved: apStar-dr17-2M16211238+3053175.fits
Saved: apStar-dr17-2M16211282+2823165.fits
Saved: apStar-dr17-2M16211285+3022467.fits
Saved: apStar-dr17-2M16211390+2633094.fits
Saved: apStar-dr17-2M16211425+3018291.fits
Saved: apStar-dr17-2M16211558+2722320.fits
Saved: apStar-dr17-2M16211572+2958089.fits
Saved: apStar-dr17-2M16211613+2850252.fits
Saved: apStar-dr17-2M16211712+2548548.fits
Saved: apStar-dr17-2M16211790+2701380.fits
Saved: apStar-dr17-2M16211796+2523250.fits
Saved: apStar-dr17-2M16211840+2942079.fits
Saved: apStar-dr17-2M16211912+2935389.fits
Saved: apStar-dr17-2M16211996+3011345.fits
Saved: apStar-dr17-2M16212141+3112290.fits
Saved: apStar-dr17-2M16212178+2501359.fits
Saved: apStar-dr17-2M16212244+2559200.fits
Saved: apStar-dr17-2M16212252+2859434.fits
Saved: apStar-dr17-2M16212253+2952195.fits
Saved: apStar-dr17-2M16212285+2730450.fits
Saved: apStar-dr17-2M16212338+2955054.fits
Saved: apStar-dr17-2M16212413+3130061.fits
Saved: apStar-dr17-2M16212413+3103269.fits
Saved: apStar-dr17-2M16212447+2858094.fits
Saved: apStar-dr17-2M16212513+2547383.fits
Saved: apStar-dr17-2M16212683+2607039.fits
Saved: apStar-dr17-2M16212686+3133151.fits
Saved: apStar-dr17-2M16212841+2524137.fits
Saved: apStar-dr17-2M16212941+2545307.fits
Saved: apStar-dr17-2M16213012+3049317.fits
Saved: apStar-dr17-2M16213100+2748537.fits
Saved: apStar-dr17-2M16213105+3055154.fits
Saved: apStar-dr17-2M16213192+2546384.fits
Saved: apStar-dr17-2M16213323+3245058.fits
Saved: apStar-dr17-2M16213496+3254384.fits
Saved: apStar-dr17-2M16213511+3021033.fits
Saved: apStar-dr17-2M16213526+3117411.fits
Saved: apStar-dr17-2M16213648+2922121.fits
Saved: apStar-dr17-2M16213667+3258562.fits
Saved: apStar-dr17-2M16213668+2628137.fits
Saved: apStar-dr17-2M16213954+2746545.fits
Saved: apStar-dr17-2M16214002+3045169.fits
Saved: apStar-dr17-2M16214072+2524386.fits
Saved: apStar-dr17-2M16214108+3057184.fits
Saved: apStar-dr17-2M16214110+2740031.fits
Saved: apStar-dr17-2M16214160+2626220.fits
Saved: apStar-dr17-2M16214231+2913136.fits
Saved: apStar-dr17-2M16214304+2522086.fits
Saved: apStar-dr17-2M16214353+2543243.fits
Saved: apStar-dr17-2M16214420+3158278.fits
Saved: apStar-dr17-2M16214428+3026044.fits
Saved: apStar-dr17-2M16214432+2537505.fits
Saved: apStar-dr17-2M16214432+2934132.fits
Saved: apStar-dr17-2M16214449+2520536.fits
Saved: apStar-dr17-2M16214488+3258415.fits
Saved: apStar-dr17-2M16214496+2729521.fits
Saved: apStar-dr17-2M16214526+3253027.fits
Saved: apStar-dr17-2M16214541+2624291.fits
Saved: apStar-dr17-2M16214602+2712163.fits
Saved: apStar-dr17-2M16214634+2607113.fits
Saved: apStar-dr17-2M16214735+2732169.fits
Saved: apStar-dr17-2M16214783+2643252.fits
Saved: apStar-dr17-2M16214932+2632237.fits
Saved: apStar-dr17-2M16214950+2638188.fits
Saved: apStar-dr17-2M16214952+3004234.fits
Saved: apStar-dr17-2M16215041+3032471.fits
Saved: apStar-dr17-2M16215095+3233444.fits
Saved: apStar-dr17-2M16215327+3029201.fits
Saved: apStar-dr17-2M16215386+2740118.fits
Saved: apStar-dr17-2M16215418+3021482.fits
Saved: apStar-dr17-2M16215593+2619081.fits
Saved: apStar-dr17-2M16215737+2746556.fits
Saved: apStar-dr17-2M16215824+2507557.fits
Saved: apStar-dr17-2M16220033+2905038.fits
Saved: apStar-dr17-2M16220101+2531099.fits
Saved: apStar-dr17-2M16220103+2730287.fits
Saved: apStar-dr17-2M16220112+2546308.fits
Saved: apStar-dr17-2M16220237+2941142.fits
Saved: apStar-dr17-2M16220305+3032558.fits
Saved: apStar-dr17-2M16220325+2555460.fits
Saved: apStar-dr17-2M16220440+2704336.fits
Saved: apStar-dr17-2M16220471+2559094.fits
Saved: apStar-dr17-2M16220488+2916436.fits
Saved: apStar-dr17-2M16220571+2608597.fits
Saved: apStar-dr17-2M16220607+3043211.fits
Saved: apStar-dr17-2M16220753+2613380.fits
Saved: apStar-dr17-2M16221118+2757193.fits
Saved: apStar-dr17-2M16221130+2520310.fits
Saved: apStar-dr17-2M16221150+2552335.fits
Saved: apStar-dr17-2M16221346+2859525.fits
Saved: apStar-dr17-2M16221486+3046044.fits
Saved: apStar-dr17-2M16221535+2533557.fits
Saved: apStar-dr17-2M16221634+3308326.fits
Saved: apStar-dr17-2M16221759+3215454.fits
Saved: apStar-dr17-2M16221770+3130590.fits
Saved: apStar-dr17-2M16221947+2555249.fits
Saved: apStar-dr17-2M16221995+3240498.fits
Saved: apStar-dr17-2M16222150+2722408.fits
Saved: apStar-dr17-2M16222270+2705184.fits
Saved: apStar-dr17-2M16222360+2505305.fits
Saved: apStar-dr17-2M16222416+2956471.fits
Saved: apStar-dr17-2M16222543+3009139.fits
Saved: apStar-dr17-2M16222647+2817545.fits
Saved: apStar-dr17-2M16222657+2604581.fits
Saved: apStar-dr17-2M16222701+3230407.fits
Saved: apStar-dr17-2M16222777+2816003.fits
Saved: apStar-dr17-2M16222806+2531575.fits
Saved: apStar-dr17-2M16222917+2558553.fits
Saved: apStar-dr17-2M16222939+3213190.fits
Saved: apStar-dr17-2M16222988+2719176.fits
Saved: apStar-dr17-2M16223296+2708560.fits
Saved: apStar-dr17-2M16223297+3306583.fits
Saved: apStar-dr17-2M16223375+2849466.fits
Saved: apStar-dr17-2M16223436+2554516.fits
Saved: apStar-dr17-2M16223617+3129000.fits
Saved: apStar-dr17-2M16223727+2612304.fits
Saved: apStar-dr17-2M16223790+2505049.fits
Saved: apStar-dr17-2M16224161+2547161.fits
Saved: apStar-dr17-2M16224183+3012271.fits
Saved: apStar-dr17-2M16224229+2539417.fits
Saved: apStar-dr17-2M16224260+2557256.fits
Saved: apStar-dr17-2M16224282+3007239.fits
Saved: apStar-dr17-2M16224385+3214549.fits
Saved: apStar-dr17-2M16224517+2559581.fits
Saved: apStar-dr17-2M16224530+3015232.fits
Saved: apStar-dr17-2M16224555+2541075.fits
Saved: apStar-dr17-2M16224574+2520099.fits
Saved: apStar-dr17-2M16224600+3107463.fits
Saved: apStar-dr17-2M16224651+2659520.fits
Saved: apStar-dr17-2M16224701+2802264.fits
Saved: apStar-dr17-2M16224765+2906206.fits
Saved: apStar-dr17-2M16224801+3103599.fits
Saved: apStar-dr17-2M16224889+3021528.fits
Saved: apStar-dr17-2M16224926+2552406.fits
Saved: apStar-dr17-2M16225040+2538280.fits
Saved: apStar-dr17-2M16225042+3023326.fits
Saved: apStar-dr17-2M16225080+3000276.fits
Saved: apStar-dr17-2M16225108+3242495.fits
Saved: apStar-dr17-2M16225142+2507457.fits
Saved: apStar-dr17-2M16225198+3035439.fits
Saved: apStar-dr17-2M16225222+2707555.fits
Saved: apStar-dr17-2M16225273+3051462.fits
Saved: apStar-dr17-2M16225279+2945259.fits
Saved: apStar-dr17-2M16225304+2706021.fits
Saved: apStar-dr17-2M16225397+3301474.fits
Saved: apStar-dr17-2M16225453+2731262.fits
Saved: apStar-dr17-2M16225563+2725305.fits
Saved: apStar-dr17-2M16225721+3220292.fits
Saved: apStar-dr17-2M16225747+2516049.fits
Saved: apStar-dr17-2M16225756+2730152.fits
Saved: apStar-dr17-2M16225814+2906158.fits
Saved: apStar-dr17-2M16225857+2640527.fits
Saved: apStar-dr17-2M16225904+2605103.fits
Saved: apStar-dr17-2M16225924+2545180.fits
Saved: apStar-dr17-2M16225990+3016471.fits
Saved: apStar-dr17-2M16230032+3307232.fits
Saved: apStar-dr17-2M16230055+3142470.fits
Saved: apStar-dr17-2M16230110+3101171.fits
Saved: apStar-dr17-2M16230118+2841523.fits
Saved: apStar-dr17-2M16230119+2942068.fits
Saved: apStar-dr17-2M16230167+2604527.fits
Saved: apStar-dr17-2M16230196+2532119.fits
Saved: apStar-dr17-2M16230299+2547263.fits
Saved: apStar-dr17-2M16230346+2554268.fits
Saved: apStar-dr17-2M16230391+2951011.fits
Saved: apStar-dr17-2M16230588+3242151.fits
Saved: apStar-dr17-2M16230614+3208221.fits
Saved: apStar-dr17-2M16230621+3206269.fits
Saved: apStar-dr17-2M16230721+3023321.fits
Saved: apStar-dr17-2M16230796+2715527.fits
Saved: apStar-dr17-2M16230872+3040080.fits
Saved: apStar-dr17-2M16231106+3201063.fits
Saved: apStar-dr17-2M16231343+2917086.fits
Saved: apStar-dr17-2M16231490+2558366.fits
Saved: apStar-dr17-2M16231509+2726142.fits
Saved: apStar-dr17-2M16231862+2656076.fits
Saved: apStar-dr17-2M16231941+2618092.fits
Saved: apStar-dr17-2M16231948+2507335.fits
Saved: apStar-dr17-2M16232058+2503437.fits
Saved: apStar-dr17-2M16232147+2547540.fits
Saved: apStar-dr17-2M16232209+2548399.fits
Saved: apStar-dr17-2M16232375+2901557.fits
Saved: apStar-dr17-2M16232388+2606542.fits
Saved: apStar-dr17-2M16232393+2834379.fits
Saved: apStar-dr17-2M16232505+3230503.fits
Saved: apStar-dr17-2M16232634+2608480.fits
Saved: apStar-dr17-2M16232664+2738569.fits
Saved: apStar-dr17-2M16232763+3002058.fits
Saved: apStar-dr17-2M16232765+2501168.fits
Saved: apStar-dr17-2M16232777+2552283.fits
Saved: apStar-dr17-2M16232777+3013511.fits
Saved: apStar-dr17-2M16232810+2703334.fits
Saved: apStar-dr17-2M16232811+2518550.fits
Saved: apStar-dr17-2M16232939+2617562.fits
Saved: apStar-dr17-2M16232967+2708032.fits
Saved: apStar-dr17-2M16233253+3030158.fits
Saved: apStar-dr17-2M16233255+3241014.fits
Saved: apStar-dr17-2M16233365+2714075.fits
Saved: apStar-dr17-2M16233434+2649314.fits
Saved: apStar-dr17-2M16233637+3040484.fits
Saved: apStar-dr17-2M16233654+2542138.fits
Saved: apStar-dr17-2M16233681+2943485.fits
Saved: apStar-dr17-2M16233742+3249179.fits
Saved: apStar-dr17-2M16233773+2930340.fits
Saved: apStar-dr17-2M16233849+3036295.fits
Saved: apStar-dr17-2M16233888+2609391.fits
Saved: apStar-dr17-2M16233952+2628510.fits
Saved: apStar-dr17-2M16234058+2912254.fits
Saved: apStar-dr17-2M16234066+2542427.fits
Saved: apStar-dr17-2M16234124+3139522.fits
Saved: apStar-dr17-2M16234232+2622224.fits
Saved: apStar-dr17-2M16234241+3035201.fits
Saved: apStar-dr17-2M16234366+2520045.fits
Saved: apStar-dr17-2M16234404+2635011.fits
Saved: apStar-dr17-2M16234439+2637210.fits
Saved: apStar-dr17-2M16234523+2548428.fits
Saved: apStar-dr17-2M16234559+3239463.fits
Saved: apStar-dr17-2M16234610+2630016.fits
Saved: apStar-dr17-2M16234686+3454134.fits
Saved: apStar-dr17-2M16234742+3038361.fits
Saved: apStar-dr17-2M16234980+3057066.fits
Saved: apStar-dr17-2M16235016+2538307.fits
Saved: apStar-dr17-2M16235030+2853325.fits
Saved: apStar-dr17-2M16235060+2517501.fits
Saved: apStar-dr17-2M16235125+2832096.fits
Saved: apStar-dr17-2M16235434+2734578.fits
Saved: apStar-dr17-2M16235448+2843172.fits
Saved: apStar-dr17-2M16235628+2500087.fits
Saved: apStar-dr17-2M16235667+2524426.fits
Saved: apStar-dr17-2M16235684+3221234.fits
Saved: apStar-dr17-2M16235741+2720207.fits
Saved: apStar-dr17-2M16235746+3036500.fits
Saved: apStar-dr17-2M16235772+2809208.fits
Saved: apStar-dr17-2M16235798+2826079.fits
Saved: apStar-dr17-2M16235806+3119160.fits
Saved: apStar-dr17-2M16235881+3043199.fits
Saved: apStar-dr17-2M16235882+3032348.fits
Saved: apStar-dr17-2M16235954+2737518.fits
Saved: apStar-dr17-2M16240151+3200208.fits
Saved: apStar-dr17-2M16240298+2932345.fits
Saved: apStar-dr17-2M16240380+2729139.fits
Saved: apStar-dr17-2M16240385+2550291.fits
Saved: apStar-dr17-2M16240481+2956487.fits
Saved: apStar-dr17-2M16240758+2914142.fits
Saved: apStar-dr17-2M16240789+2514410.fits
Saved: apStar-dr17-2M16240878+2601052.fits
Saved: apStar-dr17-2M16240937+2633344.fits
Saved: apStar-dr17-2M16241058+3226058.fits
Saved: apStar-dr17-2M16241081+2957325.fits
Saved: apStar-dr17-2M16241225+2828265.fits
Saved: apStar-dr17-2M16241245+2807441.fits
Saved: apStar-dr17-2M16241259+2551161.fits
Saved: apStar-dr17-2M16241272+2916015.fits
Saved: apStar-dr17-2M16241438+3215402.fits
Saved: apStar-dr17-2M16241443+2825428.fits
Saved: apStar-dr17-2M16241447+2703320.fits
Saved: apStar-dr17-2M16241480+3104577.fits
Saved: apStar-dr17-2M16241481+2956205.fits
Saved: apStar-dr17-2M16241489+2907407.fits
Saved: apStar-dr17-2M16241516+2608316.fits
Saved: apStar-dr17-2M16241551+2637281.fits
Saved: apStar-dr17-2M16241576+3117501.fits
Saved: apStar-dr17-2M16241664+2627444.fits
Saved: apStar-dr17-2M16241686+2559163.fits
Saved: apStar-dr17-2M16241701+2617457.fits
Saved: apStar-dr17-2M16241703+2709533.fits
Saved: apStar-dr17-2M16241742+2625036.fits
Saved: apStar-dr17-2M16241772+2556315.fits
Saved: apStar-dr17-2M16241804+3453201.fits
Saved: apStar-dr17-2M16241903+2547287.fits
Saved: apStar-dr17-2M16241914+2648431.fits
Saved: apStar-dr17-2M16241927+3204327.fits
Saved: apStar-dr17-2M16241973+3237094.fits
Saved: apStar-dr17-2M16242122+3459567.fits
Saved: apStar-dr17-2M16242230+2643070.fits
Saved: apStar-dr17-2M16242371+3046210.fits
Saved: apStar-dr17-2M16242411+3232078.fits
Saved: apStar-dr17-2M16242479+3241356.fits
Saved: apStar-dr17-2M16242673+3249575.fits
Saved: apStar-dr17-2M16242776+3203086.fits
Saved: apStar-dr17-2M16242795+2634599.fits
Saved: apStar-dr17-2M16242828+2628007.fits
Saved: apStar-dr17-2M16242841+2614407.fits
Saved: apStar-dr17-2M16242899+2614348.fits
Saved: apStar-dr17-2M16242910+2817170.fits
Saved: apStar-dr17-2M16243056+2743465.fits
Saved: apStar-dr17-2M16243205+2742367.fits
Saved: apStar-dr17-2M16243431+2913032.fits
Saved: apStar-dr17-2M16243505+2803560.fits
Saved: apStar-dr17-2M16243506+2553242.fits
Saved: apStar-dr17-2M16243580+2605062.fits
Saved: apStar-dr17-2M16243787+3457238.fits
Saved: apStar-dr17-2M16243823+2547241.fits
Saved: apStar-dr17-2M16243875+3159432.fits
Saved: apStar-dr17-2M16244020+2748491.fits
Saved: apStar-dr17-2M16244031+3205326.fits
Saved: apStar-dr17-2M16244071+2759426.fits
Saved: apStar-dr17-2M16244114+3036397.fits
Saved: apStar-dr17-2M16244370+2724525.fits
Saved: apStar-dr17-2M16244391+2741228.fits
Saved: apStar-dr17-2M16244493+2530122.fits
Saved: apStar-dr17-2M16244510+2845234.fits
Saved: apStar-dr17-2M16244566+2745149.fits
Saved: apStar-dr17-2M16244901+3059430.fits
Saved: apStar-dr17-2M16244993+3138190.fits
Saved: apStar-dr17-2M16245089+2500583.fits
Saved: apStar-dr17-2M16245098+3040181.fits
Saved: apStar-dr17-2M16245161+3026194.fits
Saved: apStar-dr17-2M16245317+2603595.fits
Saved: apStar-dr17-2M16245347+2533322.fits
Saved: apStar-dr17-2M16245381+2617452.fits
Saved: apStar-dr17-2M16245427+2845531.fits
Saved: apStar-dr17-2M16245576+3011165.fits
Saved: apStar-dr17-2M16245606+2518583.fits
Saved: apStar-dr17-2M16245738+3240073.fits
Saved: apStar-dr17-2M16245752+3023586.fits
Saved: apStar-dr17-2M16250128+2729226.fits
Saved: apStar-dr17-2M16250206+3155016.fits
Saved: apStar-dr17-2M16250220+3259406.fits
Saved: apStar-dr17-2M16250248+3115274.fits
Saved: apStar-dr17-2M16250298+2802492.fits
Saved: apStar-dr17-2M16250439+2849027.fits
Saved: apStar-dr17-2M16250460+3051503.fits
Saved: apStar-dr17-2M16250489+2750594.fits
Saved: apStar-dr17-2M16250515+3212096.fits
Saved: apStar-dr17-2M16250656+3002259.fits
Saved: apStar-dr17-2M16250768+2627123.fits
Saved: apStar-dr17-2M16250802+2716165.fits
Saved: apStar-dr17-2M16250813+3128486.fits
Saved: apStar-dr17-2M16251110+2511143.fits
Saved: apStar-dr17-2M16251175+2744075.fits
Saved: apStar-dr17-2M16251193+2747047.fits
Saved: apStar-dr17-2M16251215+3222089.fits
Saved: apStar-dr17-2M16251261+3039545.fits
Saved: apStar-dr17-2M16251261+3020154.fits
Saved: apStar-dr17-2M16251307+2551141.fits
Saved: apStar-dr17-2M16251519+2652168.fits
Saved: apStar-dr17-2M16251597+2602551.fits
Saved: apStar-dr17-2M16251647+2955266.fits
Saved: apStar-dr17-2M16251670+2620479.fits

In [1]:
#Spectral Extraction/Plotting (Cut 1)
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt
from astropy.io import fits

input_dir = Path("/Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_apStar_dr17")
output_dir = Path("/Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots")
output_dir.mkdir(parents=True, exist_ok=True)

files = sorted(input_dir.glob("*.fits"))
print(f"Found {len(files)} FITS files")


for fname in files:
    try:
        with fits.open(fname) as hdul:
            flux = hdul[1].data
            hdr = hdul[1].header

            crval1 = hdr["CRVAL1"]
            cdelt1 = hdr["CDELT1"]
            naxis1 = hdr["NAXIS1"]

            loglam = crval1 + np.arange(naxis1) * cdelt1
            wave = 10**loglam  # Angstrom

            if flux.ndim == 2:
                flux = flux[0]

        plt.figure(figsize=(14, 4))
        plt.plot(wave / 1e4, flux, lw=0.7)
        plt.xlabel("Wavelength [micron]")
        plt.ylabel("Flux")
        plt.title(fname.stem)
        plt.tight_layout()

        apogee_id = fname.stem.replace("apStar-dr17-", "")
        outpath = output_dir / f"{apogee_id}.png"
        plt.savefig(outpath, dpi=200, bbox_inches="tight")
        plt.close()

        print(f"Saved {outpath}")

    except Exception as e:
        print(f"Failed on {fname.name}: {e}")

Found 79 FITS files
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08313774-2044159.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08313948-2049340.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08314033-2045418.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08314056-2051062.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08314088-2058127.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08314312-2052081.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08314570-2035331.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08315521-2059494.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08321168-2051391.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08321319-2043170.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08322001-2051184.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08322656-2021128.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08322878-2054000.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08323600-2051321.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08323780-2050066.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08324299-2016522.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08324710-2020078.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08325349-2045139.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08325825-2012378.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08330394-2028122.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08330574-2035029.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08331081-2013217.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08331654-2018448.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08331835-2029070.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08331912-2014412.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08332169-2043474.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08332793-2040359.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08333121-2047028.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08333812-2033151.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08334573-2048405.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08335104-2012328.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08335210-2051359.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08335217-2020067.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08335463-2047536.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08335572-2041562.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08335791-2004002.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08340229-2014376.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08340273-2031397.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08340323-2027066.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08340648-2021599.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08340829-2054073.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08341165-2046019.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08341283-2015547.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08341342-2051003.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08341920-2035068.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08341967-2057116.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08341998-2048551.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08342651-2027023.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08342691-2037197.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08343072-2026076.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08343237-2039170.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08343579-2016359.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08343602-2054461.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08343773-2041329.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08343893-2020390.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08343924-2059116.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08344205-2028480.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08344493-2059058.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08344923-2055307.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08345249-2039210.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08345319-2026466.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08345402-2056053.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08350220-2037544.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08350479-2039118.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08350785-2042121.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08351453-2025370.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08351559-2052058.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08351668-2048222.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08352535-2055023.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08352980-2030481.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08353222-2059001.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08353664-2042480.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08353666-2031465.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08353880-2029321.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08354359-2044500.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08354523-2051073.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08355473-2058421.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08355771-2004513.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots/2M08355804-2039263.png

In [1]:
#Spectral Extraction/Plotting (Cut 2)
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt
from astropy.io import fits

input_dir = Path("/Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_apStar_dr17_cut2")
output_dir = Path("/Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2")
output_dir.mkdir(parents=True, exist_ok=True)

files = sorted(input_dir.glob("*.fits"))
print(f"Found {len(files)} FITS files")


for fname in files:
    try:
        with fits.open(fname) as hdul:
            flux = hdul[1].data
            hdr = hdul[1].header

            crval1 = hdr["CRVAL1"]
            cdelt1 = hdr["CDELT1"]
            naxis1 = hdr["NAXIS1"]

            loglam = crval1 + np.arange(naxis1) * cdelt1
            wave = 10**loglam  # Angstrom

            if flux.ndim == 2:
                flux = flux[0]

        plt.figure(figsize=(14, 4))
        plt.plot(wave / 1e4, flux, lw=0.7)
        plt.xlabel("Wavelength [micron]")
        plt.ylabel("Flux")
        plt.title(fname.stem)
        plt.tight_layout()

        apogee_id = fname.stem.replace("apStar-dr17-", "")
        outpath = output_dir / f"{apogee_id}.png"
        plt.savefig(outpath, dpi=200, bbox_inches="tight")
        plt.close()

        print(f"Saved {outpath}")

    except Exception as e:
        print(f"Failed on {fname.name}: {e}")

Found 3365 FITS files
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16200012+2733344.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16200058+2638119.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16200096+3029038.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16200130+3054529.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16200198+2825014.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16200223+3323551.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16200263+3300390.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16200295+2810183.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16200351+3111508.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16200366+2757487.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16200528+3240432.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16200550+3313093.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16200675+2811476.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16200695+2625173.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16200725+2804191.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16200818+3115377.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16201057+3130398.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16201156+2900436.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16201263+3226245.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16201277+2545026.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16201277+3057381.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16201504+2541172.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16201556+3104204.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16201596+2626557.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16201620+2601126.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16201734+3233338.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16201757+2630466.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16201939+2535134.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16201996+2941160.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16202072+2949414.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16202135+2839328.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16202211+3001235.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16202238+3231185.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16202346+3250114.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16202481+3128508.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16202575+2837391.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16202677+2656584.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16202689+3114372.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16202728+3332313.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16202768+3121437.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16202964+3008455.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16203067+3009193.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16203192+2507469.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16203206+3246565.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16203210+2859137.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16203221+2721407.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16203258+2650268.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16203266+2641167.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16203396+3145100.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16203413+2815395.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16203416+3132541.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16203719+2922105.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16203828+3043230.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16203840+3001190.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16203859+2718212.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16203949+2711496.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16203977+2602474.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16204053+3001538.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16204074+3014263.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16204151+2842045.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16204253+3251511.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16204259+2807299.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16204272+2533084.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16204491+2909394.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16204491+3029533.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16204541+3045244.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16204633+2732062.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16204650+3100332.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16204778+3251528.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16204865+2650061.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16204885+3001430.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16204905+3005455.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16204940+3135149.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16204962+2911190.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16205013+3109052.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16205022+3220497.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16205058+2558427.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16205088+2737569.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16205186+2708409.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16205233+3139411.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16205268+2702531.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16205341+2909073.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16205349+3112318.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16205392+2902324.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16205477+2627207.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16205478+2645565.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16205487+3228434.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16205572+3050259.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16205774+3231494.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16205785+3200539.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16205795+2905569.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16205841+2609493.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16210081+2734394.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16210111+2805040.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16210173+2654437.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16210196+3028338.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16210271+2512409.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16210280+3246472.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16210338+3301255.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16210354+3014432.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16210355+3025489.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16210374+3240135.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16210379+2536384.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16210394+2533024.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16210408+2630009.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16210469+2508001.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16210600+2944239.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16210611+2814163.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16210688+3041325.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16210714+3134367.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16210715+2552117.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16210741+2553060.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16210787+3205492.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16210830+3155207.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16210896+2920517.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16210923+2539227.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16211033+2855524.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16211086+2515010.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16211096+2630456.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16211238+3053175.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16211282+2823165.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16211285+3022467.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16211390+2633094.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16211425+3018291.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16211558+2722320.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16211572+2958089.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16211613+2850252.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16211712+2548548.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16211790+2701380.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16211796+2523250.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16211840+2942079.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16211912+2935389.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16211996+3011345.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16212141+3112290.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16212178+2501359.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16212244+2559200.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16212252+2859434.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16212253+2952195.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16212285+2730450.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16212338+2955054.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16212413+3103269.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16212413+3130061.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16212447+2858094.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16212513+2547383.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16212683+2607039.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16212686+3133151.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16212841+2524137.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16212941+2545307.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16213012+3049317.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16213100+2748537.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16213105+3055154.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16213192+2546384.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16213323+3245058.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16213496+3254384.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16213511+3021033.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16213526+3117411.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16213648+2922121.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16213667+3258562.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16213668+2628137.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16213954+2746545.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16214002+3045169.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16214072+2524386.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16214108+3057184.png

WARNING: File may have been truncated: actual file length (106496) is smaller than the expected size (149760) [astropy.io.fits.file]

Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16531283+2705098.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16531290+2557170.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16531365+3414261.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16531497+2802538.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16531575+3318362.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16531586+3425277.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16531697+2610289.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16531709+2509097.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16531727+3439022.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16531755+2559077.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16531907+2553506.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16531949+2503546.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16531989+2848570.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16532109+2909269.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16532117+3158327.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16532242+2548305.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16532258+3259589.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16532507+2617197.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16532665+3406406.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16532753+3002593.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16532860+3301240.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16532946+3053356.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16532967+3225385.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16532993+2502258.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16533026+3409370.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16533109+2554003.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16533171+3055484.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16533316+3129290.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16533318+2756437.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16533359+3337116.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16533443+3318134.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16533548+3456258.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16533558+2555219.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16533564+2641363.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16533599+2841228.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16533679+2855308.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16533697+2811556.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16533789+2801050.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16533854+2853335.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16533886+2657172.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16534097+3142429.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16534099+3424284.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16534114+3251541.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16534219+3208078.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16534220+3112043.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16534245+3448085.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16534277+3432569.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16534336+3237228.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16534341+2624458.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16534440+3232000.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16534547+3205469.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16534583+2531166.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16534594+2548159.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16535107+3436268.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16535158+3109342.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16535180+2655081.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16535204+3432400.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16535233+2525314.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16535249+2756086.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16535259+3251470.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16535306+2610487.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16535313+3414503.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16535408+2639539.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16535423+2547046.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16535495+2623148.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16535549+2859246.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16535569+3300174.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16535754+3038438.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16535770+2656476.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16535831+2543358.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16535834+3121384.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16535921+2830332.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16535940+2800205.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16535980+2906230.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16540011+2559248.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16540098+3003160.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16540254+3412080.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16540268+2829179.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16540276+3401166.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16540319+3242258.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16540324+3147572.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16540352+3049292.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16540402+3127036.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16540404+2645494.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16540484+2817454.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16540566+3110578.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16540703+3108396.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16540801+3431132.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16540842+2632586.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16540997+3224474.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16541172+3250575.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16541334+2829541.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16541371+2738579.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16541618+3104315.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16541651+3324546.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16541694+3126150.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16541704+3419267.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16541712+3342111.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16541785+2909252.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16541834+3131193.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16541873+3039461.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16541912+2537363.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16541999+2531152.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16542272+2618206.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16542275+2620003.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16542333+2635254.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16542367+2534164.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16542369+3443137.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16542423+3309439.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16542471+3330530.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16542554+2643109.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16542564+2509590.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16542567+2625125.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16542591+2709028.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16542627+3113370.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16542841+2911355.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16542861+2848512.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16542902+2818437.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16542961+2725076.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16542988+3459475.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16543006+2608205.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16543151+2810519.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16543248+2623100.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16543421+3227311.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16543514+3222505.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16543556+3431099.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16543604+3302279.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16543725+3406237.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16543802+2627448.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16543909+3026427.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16543910+2638167.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16544167+3122248.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16544233+2529452.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16544411+2502238.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16544418+2826454.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16544446+2840062.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16544549+3244103.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16544584+2627383.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16544589+3222396.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16544595+3415119.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16544603+3035363.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16544874+2555187.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16544922+3024033.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16544979+3253000.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16544990+2734172.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16545085+3254400.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16545113+3116375.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16545147+3346440.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16545210+3109346.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16545383+2650246.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16545721+2728260.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16545826+2805513.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16545947+3135032.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16550143+3328089.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16550201+3108049.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16550206+3405520.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16550287+3257408.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16550372+3013259.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16550387+2814125.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16550406+2759362.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16550445+2840397.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16550642+2548237.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16550682+3238372.png

WARNING: File may have been truncated: actual file length (286720) is smaller than the expected size (290880) [astropy.io.fits.file]

Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16551984+3048183.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16552070+3231489.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16552222+2852313.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16552261+2502395.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16552301+3358099.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16552356+3258504.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16552382+3234413.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16552391+2811151.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16552450+3144302.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16552528+2715427.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16552564+3034147.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16552634+2656471.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16552763+3236052.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16552793+3045413.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16552819+2536539.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16552921+3208318.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16553074+2908451.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16553168+2621483.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16553199+2512079.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16553262+3449488.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16553352+3114290.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16553533+2632116.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16553558+3216544.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16553584+2626287.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16553608+2823593.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16553611+3139330.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16553650+3046171.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16553766+2906251.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16553966+2811332.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16554019+3242146.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16554068+3456238.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16554183+2512149.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16554190+3145489.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16554235+3231504.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16554340+2628366.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16554471+3120097.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16554542+3441451.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16554565+3105336.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16554578+2905237.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16554722+2756102.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16554775+3256582.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16554805+3040215.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16554818+2601099.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16554989+3037435.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16555018+3134542.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16555126+3409001.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16555137+2806027.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16555209+2616143.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16555215+2631560.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16555241+3256194.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16555312+3149307.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16555324+2645268.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16555512+2532008.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16555611+3126455.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16555622+2641097.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16555824+2714128.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16555882+3250486.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16555883+3431546.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16555935+3213184.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16555957+2754376.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16555958+3401354.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16560181+3310399.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16560392+2908453.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16560573+2501333.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16560608+2828463.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16560660+3349178.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16560686+2520316.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16560688+3346145.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16560794+2723219.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16561113+2506474.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16561294+3244032.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16561299+2612075.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16561338+3145201.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16561359+3302289.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16561395+3305193.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16561531+2905510.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16561594+3158254.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16561714+3345388.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16561745+2818338.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16561840+3413489.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16561860+2537506.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16561876+3128099.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16561893+3228101.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16562090+3151244.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16562155+2602127.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16562188+3225052.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16562188+3235082.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16562287+3143380.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16562381+2832234.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16562409+2635499.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16562474+3110155.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16562495+2901429.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16562511+3334243.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16562583+2556227.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16562629+3259209.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16562673+2508483.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16562718+3151359.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16562725+3357541.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16562769+2816284.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16562851+2503489.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16562936+2625433.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16563002+3328407.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16563004+2904116.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16563012+2745018.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16563020+2527003.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16563267+2615061.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16563356+3228402.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16563386+3053136.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16563419+3354221.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16563507+3037303.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16563756+3115510.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16563768+3203330.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16563819+3425526.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16563946+2730045.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16564006+2640353.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16564218+2705013.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16564457+2830434.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16564513+3108230.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16564552+2903521.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16564558+2520224.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16564580+2541013.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16564581+2644331.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16564599+3036404.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16564604+2838296.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16564670+2732312.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16564670+3447255.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16564736+3419429.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16565040+3304274.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16565046+2521568.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16565162+2620096.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16565186+2753541.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16565239+3048568.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16565241+2516193.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16565243+2819181.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16565421+3357137.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16565469+2755557.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16565522+3035241.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16565536+3130527.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16565558+2515598.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16565636+3325307.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16565830+2534278.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16565974+2845460.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16570002+3125082.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16570019+2623232.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16570027+3139439.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16570552+3201580.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16570704+3026516.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16570779+3242046.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16570796+3207136.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16570814+3303353.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16570848+2542458.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16570883+3218063.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16571062+3114541.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16571243+3239330.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16571280+3350166.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16571283+3304169.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16571324+3023377.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16571379+3042125.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16571450+3323146.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16571472+3047286.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16571536+3251572.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16571583+3150317.png
Saved /Users/sarahstamer/Desktop/Grad/2025-2026/ASTR_526/Project/APOGEE/apogee_spectrum_plots_cut2/2M16571622+3250125.png